* Clops-Gui

A system that uses cl-gtk4 and allows other apps to use its GUI capabilities for
drawing canvas, menu and events. Quite limited subset of Gtk4 capabilities has
been implemented, but it may be enough for simple 2D graphics or games.

So far it can only do multiple windows that contain only one widget, that is
DrawingArea. The examples folder will contain examples of using the system.

There is a limitation https://github.com/bohonghuang/cl-gtk4/issues/58 of what
the underlying library can do, so you may have to implement your own widget
system similar to those in Smalltalk systems.

Perhaps it would be possible to have a declarative way to define other widgets
than DrawingArea, in similar manner to function ~menu-bar-menu~ is used for menu,
but that is not my priority.

** Usage

#+begin_src lisp
  (load "~/Programming/Lisp/clops-gui/examples/example.lisp")
#+end_src

** Installation

You need SBCL, quicklisp and ultralisp. Please follow the relevant instructions.

also install development libraries

#+begin_example
sudo apt install libgtk-4-dev
#+end_example

** coding conventions

discussion about prepending functions with %
https://www.reddit.com/r/Common_Lisp/comments/jgj9lu/naming_conventions/

And some programmers will name particularly low-level functions with names that start with % or even %%.
https://gigamonkeys.com/book/syntax-and-semantics

*** links
http://www.mohamedelafrit.com/education/ENSEIRB/lisp/standards.pdf

https://ccrma.stanford.edu/CCRMA/Courses/AlgoComp/cm/doc/contrib/lispstyle.html
https://lisp-lang.org/style-guide/

https://github.com/bbatsov/emacs-lisp-style-guide

https://www.cliki.net/naming+conventions

https://softwareengineering.stackexchange.com/questions/363084/use-labels-or-nested-flet

*** linting

#+begin_example
CL-USER> (ql:quickload :sblint)
CL-USER> (sblint:run-lint-directory "~/Programming/Lisp/clops-gui/")
#+end_example


** notes

*** moving to app
file:~/Programming/Lisp/clops-gui/examples/example.lisp::1

*** remove gui-box from gui-window
[[file:src/gui-window.lisp::(defmethod add-child]] and the method below need to be
somehow moved to gui-box

** Great ideas

*** Archy
https://en.wikipedia.org/wiki/Archy_(software)

#+begin_quote
Archy has been compared as similar to the Emacs text editor, although its design
begins from a clean slate.
#+end_quote
